# Generated by Django 4.1.4 on 2023-01-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_is_active_alter_account_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='picture',
            field=models.ImageField(null=True, upload_to='uploads/accounts/images/%Y/%m/%d', verbose_name='UserPicture'),
        ),
    ]
