# Generated by Django 4.1.4 on 2023-01-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='picture',
            field=models.ImageField(null=True, upload_to='uploads/accounts/images/%Y/%m/%d', verbose_name='User picture'),
        ),
    ]
