# Generated by Django 4.1.4 on 2022-12-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='fawesome',
            field=models.TextField(blank=True),
        ),
    ]
