# Generated by Django 4.1.4 on 2022-12-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_fawesome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='fawesome',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
