# Generated by Django 4.1.4 on 2022-12-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='images',
            field=models.ImageField(upload_to='products/p/%Y/%m/%d'),
        ),
    ]
